language: go
os: linux
dist: xenial
go:
- 1.15
before_deploy:
- "./script/setup"
deploy:
  on:
    tags: true
  provider: releases
  file_glob: true
  file: dist/artifacts/*
  token:
    secure: m8F4qWwQgynnkF2GHfBsDrTkJEPR/bM6YkUbhcdpYtLU5wZRatrR6Cdk7/oroq79VRblV/5RlVZld0xIRJRUWjcwBhsu/lo/G3hnOtSqcHtCNesCrXbgwT+r7dWfAuQTEWsobBD9UjSsGV6pcZmCJfncmr6MeKrUcnC6gkM9riwsLfj48imBf9D90r62YWlmYvVGUaqtfOY29IsFSnwf/5X7s1u1FVx3jisMgLkVM8PMDd2wvM1MMsiJfKj43vpZu8neEjpr38USGOqO3YMPehTwa1GmPirm74lN/O/ArbsiT8QZq6gWmHm/9cjkPhcby3VHybRVRjlW5mAfit7gs0x7hhRWIyhw/zjqDOt8n7QFEla/SShxAigmkSb8BFandU2aBkrk9Ww9e8pUr6iDYgybmgr71fy+3sLV0QLdzyE2qRT5USk8jiNxDj2efhTmTq48Q8oXTKUlAB/cqwuk/eV7njznzOCDaq4co+S4yB8J6Ys2cy30/Nn2aGy9yveeKCRJrYHo1A1vNvJodu4jEOm2qcwV5Pd/AHTwG2/V4x5/RgA5fkeaWFnZvY2lBqnxdzq5C/6XYF4r/8BTjMjrZ3LZK3XVp2qAWAfQK7GTPac5syYCyRZLiS8SJvfIhTj9jshNoWFmUU6NC6AmL1d0KUKFIClebjPsBHUtwpYKk6U=
