#!/bin/sh -xe

rm -rf dist/artifacts
mkdir dist/artifacts

# TODO put back export GOOS=linux GOARCH=armv6l
go build -o dist/pihub/pihub ./main.go

archive_name=pihub-${TRAVIS_TAG}.tar.gz
archive_path=dist/artifacts/${archive_name}
tar -czvf $archive_path dist/pihub/ -C dist/

cat $archive_path | sha256sum > ${archive_path}.sha

script_name=pihub-${TRAVIS_TAG}-install.sh
tee dist/artifacts/pihub-${TRAVIS_TAG}-install.sh << EOF
#!/bin/sh -xe

wget https://github.com/xanderflood/pihub/releases/download/${TRAVIS_TAG}/${archive_name} -O /tmp/${archive_name}

# TODO chec the sha
tar -xzvf /tmp/${archive_name} ./pihub

cd ./pihub
./install
EOF

chmod +x dist/artifacts/pihub-${TRAVIS_TAG}-install.sh

wget https://github.com/xanderflood/pihub/releases/download/test3/pihub-test3-install.sh -o /tmp/${archive_name}
